### ISSUE TITLE
Cant create Items via Editor

### ISSUE THREAD

**Issue by TobiasReyEye** [moglerdev/ShelfGuardian#30]
-Trying to create a new Item with all Info --> "Something went wrong"-message is shown.
-Without missing Date --> LoadigPage is shown

**Comment by moglerdev** [comment]
@TobiasReyEye 
Can you specify what exactly you did?

**Comment by TobiasReyEye** [comment]
First Issue seems to have only occured, because of some interference with an not signed in User.

Second One: - Opening Editor  -> Typing in a Productname (other Fields are Empty) -> hitting Save -> Loading Page is shown, rather than giving me the opportunity to fill missing fields.
