### ISSUE TITLE
Scanner throws Exception when comming from EditorPage

### ISSUE THREAD

**Issue by TobiasReyEye** [moglerdev/ShelfGuardian#32]
-Scanner maybe gets opened a second Time?

**Comment by moglerdev** [comment]
@TobiasReyEye @jonaboecker 
for the future; please, when you get an exception send the exception <3 or a screenshot of it

Does the error come when your app gets reloaded?

**Comment by jonaboecker** [comment]
![Screenshot_20240701-154005.png](https://github.com/moglerdev/ShelfGuardian/assets/90841615/66e4083d-3b0e-49bb-94a8-65db08e6dade)

It occurs when you enter the scanner from the Editor via new "to scanner Button" after you alredy scanned a product. 

When you go back and open the scanner again it works fine.
